name: Rust CI

on:
  push:
    branches: [ main, trying ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: rustup toolchain install stable --no-self-update --profile minimal
    - name: Check formatting
      run: cargo fmt --all --check

  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [imxrt1176_cm7, imxrt1176_cm4, imxrt1062, imxrt1061, imxrt1052, imxrt1051, imxrt1021]
    steps:
    - uses: actions/checkout@v6
    - run: rustup toolchain install stable --no-self-update --profile minimal --target thumbv7em-none-eabihf
    - name: Check the package with supported chips
      run: cargo check --features=imxrt-ral/${{ matrix.chip }},smoltcp/socket-udp --target=x86_64-unknown-linux-gnu --target=thumbv7em-none-eabihf

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install a stable toolchain with clippy
      run: rustup toolchain install stable --no-self-update --profile minimal --component clippy --target thumbv7em-none-eabihf
    - name: Lint the package for host, target builds
      run: cargo clippy --features=imxrt-ral/imxrt1062,smoltcp/socket-udp --target=x86_64-unknown-linux-gnu --target=thumbv7em-none-eabihf -- -D warnings
    - name: Lint the package for host, target builds with defmt
      run: cargo clippy --features=imxrt-ral/imxrt1062,smoltcp/socket-udp,defmt --target=x86_64-unknown-linux-gnu --target=thumbv7em-none-eabihf -- -D warnings

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: rustup toolchain install stable --no-self-update --profile minimal
    - name: Run tests
      run: cargo test --features=imxrt-ral/imxrt1062,smoltcp/socket-udp

  docs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
    steps:
    - uses: actions/checkout@v6
    - run: rustup toolchain install stable --no-self-update --profile minimal
    - name: Check documentation
      run: cargo rustdoc --features=imxrt-ral/imxrt1062,smoltcp/socket-udp
